# Generated by Django 4.2.24 on 2025-10-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_session_key_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(blank=True, help_text='URL to profile picture', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'รอชำระเงิน'), ('paid', 'ชำระเงินแล้ว'), ('shipping', 'กำลังจัดส่ง'), ('delivered', 'จัดส่งสำเร็จ')], default='pending', max_length=50),
        ),
    ]
